version: 2

workflows:
  version: 2
  full_test:
    jobs:
      - prep-deps-npm
      - prep-deps-firefox
      - prep-build:
          requires:
            - prep-deps-npm
      - prep-docs:
          requires:
            - prep-deps-npm
      - prep-scss:
          requires:
            - prep-deps-npm
      - job-screens:
          requires:
            - prep-deps-npm
            - prep-build
      - job-publish-prerelease:
          requires:
            - prep-deps-npm
            - prep-build
            - job-screens
      - job-publish-release:
          requires:
            - prep-deps-npm
            - prep-build
            - prep-docs
            - job-screens

jobs:
  prep-deps-npm:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-
      - run:
          name: Install npm 6 + deps via npm
          command: |
           sudo npm install -g npm@6.1.0 && npm install
      - save_cache:
          key: dependency-cache-
          paths:
            - node_modules

  prep-deps-firefox:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-firefox-
      - run:
          name: Download Firefox If needed
          command: ./.circleci/scripts/firefox-download.sh
      - save_cache:
          key: dependency-cache-firefox-
          paths:
            - firefox

  prep-build:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-
      - run:
          name: build:dist
          command: npm run dist
      - run:
          name: build:debug
          command: find dist/ -type f -exec md5sum {} \; | sort -k 2
      - save_cache:
          key: build-cache-{{ .Revision }}
          paths:
            - dist
            - builds

  prep-docs:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-
      - run:
          name: build:dist
          command: npm run doc
      - save_cache:
          key: docs-cache-{{ .Revision }}
          paths:
            - docs/jsdoc

  prep-scss:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-
      - run:
          name: Get Scss Cache key
          # this allows us to checksum against a whole directory
          command: find ui/app/css -type f -exec md5sum {} \; | sort -k 2 > scss_checksum
      - run:
          name: Build for integration tests
          command: npm run test:integration:build
      - save_cache:
          key: scss-cache-{{ checksum "scss_checksum" }}
          paths:
            - ui/app/css/output

  job-screens:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Test
          command: npm run test:screens
      - save_cache:
          key: job-screens-{{ .Revision }}
          paths:
            - test-artifacts

  job-publish-prerelease:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - restore_cache:
          key: job-screens-{{ .Revision }}
      - store_artifacts:
          path: dist/mascara
          destination: builds/mascara
      - store_artifacts:
          path: dist/sourcemaps
          destination: builds/sourcemaps
      - store_artifacts:
          path: builds
          destination: builds
      - store_artifacts:
          path: test-artifacts
          destination: test-artifacts
      - run:
          name: build:announce
          command: ./development/metamaskbot-build-announce.js

  job-publish-release:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - restore_cache:
          key: docs-cache-{{ .Revision }}
      - restore_cache:
          key: job-screens-{{ .Revision }}
      - run:
          name: sentry sourcemaps upload
          command: npm run sentry:publish
      - run:
          name: github gh-pages docs publish
          command: >
            git config user.name metamaskbot
            git config user.email admin@metamask.io
            gh-pages -d docs/jsdocs

